export const TEST = {
  suite: 'Shared local TTS API routing',
  managed: 'uses the server endpoint and model instead of client-supplied cloud values',
  customDisabled: 'rejects a saved custom cloud speech provider in local-only mode',
  customProvider: 'custom-tts-saved-cloud',
  disabled: 'rejects cloud speech in explicit local mode without an upstream call',
  unavailable: 'reports an unavailable local service without a fallback request',
  url: 'http://localhost/api/generate/tts',
  remote: 'https://example.com/v1',
  text: 'Hello from local speech.',
  audioId: 'local-speech-test',
  wrongModel: 'unrelated-model',
  key: 'client-key-must-not-be-sent',
  cloud: 'qwen-tts',
  cloudVoice: 'Cherry',
  baseEnv: 'TTS_MLX_BASE_URL',
  modelsEnv: 'TTS_MLX_MODELS',
  disabledEnv: 'TTS_QWEN_ENABLED',
  disabledValue: 'false',
} as const;
